version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ubuntu2
      MYSQL_PASSWORD: ubuntu2
      MYSQL_DB: two_tier_database
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_USER: ubuntu2
      MYSQL_PASSWORD: ubuntu2
      MYSQL_DATABASE: two_tier_database
    volumes:
      - db_datanew:/var/lib/mysql
volumes:
  db_datanew:
